# Specify a base image
FROM node:16-alpine

#Set working directory
WORKDIR /app
# Install some depenendencies
COPY ./package.json ./
RUN npm install

COPY ./ ./

#Default command
CMD [ "npm", "run", "start" ]